[theme]
primaryColor = "#8f5c32"
backgroundColor = "#f7f3eb"
secondaryBackgroundColor = "#fffdf5"
textColor = "#3e3122"
font = "sans serif"
borderColor = "#a8835d"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "medium"
buttonRadius = "medium"
